# =========================================================
# DADK 应用程序黑名单配置文件模板
# 路径: config/app-blocklist.toml
# =========================================================
# 
# 应用程序黑名单功能允许用户指定不希望编译和安装的应用程序。
# 当黑名单中的应用程序被检测到时，DADK 会根据配置自动跳过这些应用程序的构建和安装过程。

# =========================================================
# 全局配置选项
# =========================================================

# 是否启用严格模式（可选）
# - true（默认）：严格模式，跳过被屏蔽的应用程序并记录警告
# - false：非严格模式，只记录警告但不跳过应用程序
strict = true

# 是否在日志中显示被跳过的应用（可选）
# - true（默认）：在日志中显示被跳过的应用程序信息
# - false：静默模式，不显示被跳过的应用程序
log_skipped = true

# =========================================================
# 被屏蔽的应用程序列表
# =========================================================
# 
# 支持以下匹配方式：
# 1. 精确匹配：            name = "app1"
# 2. 版本匹配：            name = "openssl@1.1.1"  
# 3. 通配符名称：          name = "test-*"
# 4. 通配符版本：          name = "nginx@1.*"
# 5. 复合模式：            name = "lib*@2.*"
#
# 每个应用可以选择性地提供屏蔽原因(reason)

# -------------------------
# 精确匹配示例
# -------------------------
# 屏蔽特定应用程序
[[blocked_apps]]
name = "busybox"
reason = "已被musl libc取代，不再需要"

[[blocked_apps]]
name = "deprecated-app"
reason = "应用程序已弃用"

# 无reason的应用（reason字段可选）
[[blocked_apps]]
name = "test-app"

# -------------------------
# 版本匹配示例
# -------------------------
# 屏蔽特定版本的应用程序
[[blocked_apps]]
name = "openssl@1.1.1"
reason = "存在安全漏洞CVE-2021-3711，请使用3.x版本"

[[blocked_apps]]
name = "nginx@1.18.0"
reason = "存在已知bug，建议使用1.20.0及以上版本"

# -------------------------
# 通配符模式匹配示例
# -------------------------
# 屏蔽所有测试应用程序
[[blocked_apps]]
name = "test-*"
reason = "测试应用程序，生产环境不需要"

# 屏蔽所有以"old-"开头的应用
[[blocked_apps]]
name = "old-*"
reason = "旧版本应用程序"

# 屏蔽所有debug工具
[[blocked_apps]]
name = "*-debug"
reason = "调试工具，发布版本不需要"

# -------------------------
# 版本通配符匹配示例
# -------------------------
# 屏蔽所有nginx版本
[[blocked_apps]]
name = "nginx@*"
reason = "当前项目不需要Web服务器"

# 屏蔽特定主版本的所有版本
[[blocked_apps]]
name = "libfoo@2.*"
reason = "2.x版本不兼容当前系统"

# 屏蔽特定模式的版本
[[blocked_apps]]
name = "lib*@1.*"
reason = "所有lib开头的1.x版本库都已过时"

# -------------------------
# 安全相关屏蔽示例
# -------------------------
[[blocked_apps]]
name = "curl@7.58.*"
reason = "存在安全漏洞CVE-2018-16842"

[[blocked_apps]]
name = "sqlite3@3.31.*"
reason = "存在数据损坏风险"

# -------------------------
# 架构相关屏蔽示例
# -------------------------
[[blocked_apps]]
name = "x86-*"
reason = "当前构建目标不是x86架构"

# -------------------------
# 依赖冲突屏蔽示例
# -------------------------
[[blocked_apps]]
name = "conflicting-lib"
reason = "与主要依赖库存在冲突"

# =========================================================
# 配置说明和注意事项
# =========================================================
#
# 1. **依赖关系**：如果其他应用程序依赖被屏蔽的应用程序，构建过程可能会失败。
#    请确保处理好依赖关系。
#
# 2. **模式匹配优先级**：
#    - 精确匹配 > 版本匹配 > 模式匹配
#    - 如果有多个模式都匹配，使用第一个匹配的结果
#
# 3. **通配符语法**：
#    - "*" 匹配任意数量的字符（包括0个）
#    - "?" 匹配单个字符
#    - 支持在名称和版本中使用通配符
#
# 4. **版本格式**：
#    - 版本号使用 "@" 符号分隔，如 "app@1.0.0"
#    - 版本号支持通配符，如 "app@1.*"
#
# 5. **配置文件路径**：
#    - 默认路径：config/app-blocklist.toml
#    - 可在 dadk-manifest.toml 中通过 app-blocklist-config 字段自定义路径
#
# 6. **字段说明**：
#    - name：应用程序名称或匹配模式（必需）
#    - reason：屏蔽原因说明（可选，建议提供以便调试和维护）
#    - strict：全局严格模式开关
#    - log_skipped：全局日志记录开关