name = "userapp_test_git"
version = "0.2.0"
description = ""
build-once = true
install-once = true
target-arch = ["x86_64"]

[task-source]
type = "build_from_source"
source = "git"
source-path = "https://git.mirrors.dragonos.org.cn/DragonOS-Community/test_git.git"
revision = "01cdc56863"
branch = "test"

[build]
build-command = "make install"

[install]
in-dragonos-path = "/bin"

[clean]
clean-command = "make clean"

[[depend]]
name = "depend1"
version = "0.1.1"

[[depend]]
name = "depend2"
version = "0.1.2"

[[env]]
key = "PATH"
value = "/usr/bin"

[[env]]
key = "LD_LIBRARY_PATH"
value = "/usr/lib"
