name = "test_git"
version = "0.1.0"
description = ""
build-once = true
install-once = true
target-arch = ["x86_64"]

[task-type]
type = "build_from_source"
source = "git"
source-path = "https://git.mirrors.dragonos.org.cn/DragonOS-Community/test_git.git"
revison = "01cdc56863"
branch = "test"

[build]
build-command = "make instal"

[install]
in-dragonos-path = "/bin"

[clean]
clean-command = "make clean"

[depends]
depend1 = "0.1.1"
depend2 = "0.1.2"

[envs]
PATH = "/usr/bin"
LD_LIBRARY_PATH = "/usr/lib"
