# Configuration template placed in the root directory of the DragonOS workspace
# Named `dadk-manifest.toml`

[metadata]
# Target architecture. Options: x86_64, riscv64
arch = "x86_64"

# Hypervisor config path
hypervisor_config = "config/hypervisor.toml"

# RootFS config path
rootfs_config = "config/rootfs.toml"

# Boot config path
boot_config = "config/boot.toml"
