name = "test_local"
version = "0.1.0"
description = ""
build-once = true
install-once = true
target-arch = ["x86_64"]

[task-type]
type = "install_from_prebuilt"
source = "local"
source-path = "/home/dev/demo"


[build]
build-command = "make instal"

[install]
in-dragonos-path = "/bin"

[clean]
clean-command = "make clean"

[depends]
depend1 = "0.1.1"
depend2 = "0.1.2"

[envs]
PATH = "/usr/bin"
LD_LIBRARY_PATH = "/usr/lib"
